pipelines:
  - name: test_pipeline
    steps:   
      - name: test_pipeline
        type: Bash
        configuration:
          runtime:
            type: host
        execution:
          onExecute:
            - echo "Hello from pipelines"